### ISSUE TITLE
Phpstorm - crash v0.2, error on NeonParser.java:40

### ISSUE THREAD

**Issue by kubinpetr** [juzna/intellij-neon#31]
```
Tokens [[Neon] indent, [Neon] literal, [Neon] :, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] string, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] literal, [Neon] :, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] literal, [Neon] :, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] string, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] literal, [Neon] :, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] indent, [Neon] literal, [Neon] :, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] (, [Neon] literal, [Neon] ), [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] indent, [Neon] comment, [Neon] indent, [Neon] -, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] indent, [Neon] comment, [Neon] indent, [Neon] -, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] -, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] indent, [Neon] literal, [Neon] :, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] literal, [Neon] :, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] string, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] string, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] string, [Neon] indent, [Neon] literal, [Neon] :, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] literal, [Neon] :, WHITE_SPACE, [Neon] literal, [Neon] indent, [Neon] indent, [Neon] literal, [Neon] :, [Neon] indent, [Neon] -, WHITE_SPACE, [Neon] literal, [Neon] indent] were not inserted into the tree. Language: neon, Text:

#
# Content of my neon
#

java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.lang.impl.PsiBuilderImpl.f(PsiBuilderImpl.java:1149)
	at com.intellij.lang.impl.PsiBuilderImpl.e(PsiBuilderImpl.java:1022)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:1007)
	at cz.juzna.intellij.neon.parser.NeonParser.parse(NeonParser.java:40)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:64)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.f(LazyParseableElement.java:172)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:301)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:246)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.a(BlockSupportImpl.java:194)
	at com.intellij.psi.impl.source.text.BlockSupportImpl.reparseRange(BlockSupportImpl.java:138)
	at com.intellij.psi.impl.DocumentCommitProcessor.doCommit(DocumentCommitProcessor.java:123)
	at com.intellij.psi.impl.DocumentCommitThread$4.run(DocumentCommitThread.java:474)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1143)
	at com.intellij.psi.impl.DocumentCommitThread.a(DocumentCommitThread.java:486)
	at com.intellij.psi.impl.DocumentCommitThread.access$400(DocumentCommitThread.java:53)
	at com.intellij.psi.impl.DocumentCommitThread$3.run(DocumentCommitThread.java:353)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.psi.impl.DocumentCommitThread.c(DocumentCommitThread.java:350)
	at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:294)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by JanTvrdik** [comment]
The parser should be entirely rewritten with [GrammarKit](https://github.com/JetBrains/Grammar-Kit) to avoid these kind of problems altogether.

**Comment by kubinpetr** [comment]
Ok,.... Do you now when will be released  new version, fixed version?
It is very useful, but buggy. :)

**Comment by JanTvrdik** [comment]
Hopefully this year.

**Comment by kubinpetr** [comment]
:D Ok, I deserved it. ;)

**Comment by ice1000** [comment]
What should I say...
